### ISSUE TITLE
README

### ISSUE THREAD

**Issue by tachibanayu24** [Hiroto-Nagashima/communication_notebook#3]
日本語で、環境構築手順を書いてください。
その他に、テストなど環境があれば、その手順も書いてください、

**Comment by Hiroto-Nagashima** [comment]
@tachibanayu24  環境構築手順というかアプリの使用手順を書きました。READMEを確認してくれませんか？テストに関してはテストを書くフェーズになったら書きます。問題あれば言ってください

**Comment by tachibanayu24** [comment]
うーん少し雑ですね。。

* Usageなのにこのアプリケーション内のコンポーネント名を使っている
* 変換できていなかったり、大文字であるべき部分が小文字になっていたりする
* リスト内で語調が不統一(語尾が入力、選択、、となっていて一つだけ「おす」)
* rootページやTopページと明確でない指示

また、READMEにはローカル開発環境の構築手順やテスト実行手順を書いてください
他のプロジェクトのREADMEを参考にしてください
（Usageはwikiに書いて、そのwikiのリンクをREADMEに貼るとかでも良いと思います）

**Comment by Hiroto-Nagashima** [comment]
@tachibanayu24 usageは今回無くしました。新しく書いてみたので軽く目を通していただけると嬉しいです。

**Comment by Hiroto-Nagashima** [comment]
@tachibanayu24  テストの欄も更新できましたので、READMEはこれで一区切りしようと思いますが大丈夫でしょうか？

**Comment by tachibanayu24** [comment]
@Hiroto-Nagashima 
セクションの粒度はいいと思います！

ただ、出力されているものをちゃんと確認していますか？
inline-codeになっていない部分がありますね

![Screen Shot 2021-04-27 at 10 52 33](https://user-images.githubusercontent.com/23476543/116173058-d5b6ac00-a746-11eb-9748-36a7debef009.png)


また、原則コマンドはinline-codeではなく、code-blockで書きます

```sh
$ echo 例えばこんなふうに
```

それと、setupを実行しただけではsetupできませんよね
API側の起動手順がないです。

以下のようにしてはどうですか？

---

## Setup

### API

```sh
$ docker-compose build
$ docker-compose up
```

http://localhost:xxxx でAPIサーバが起動します

### Frontend

```sh
$ cd frontend
$ yarn install
$ yarn start
```

http://localhost:xxxx でWebpackサーバが起動します

**Comment by Hiroto-Nagashima** [comment]
@tachibanayu24 ありがとうございます！setup参考にしました！そしてstorybookとswaggerの項目も追加しました
